import { Material } from '@/entities/material/model/types';
import { Part } from '@/entities/part/model/types';
import { OptimizationInput, OptimizationOptionsDto } from '@/shared/api/optimizer.dto';

export interface OptimizationInputExample extends OptimizationInput {
  name: string;
}

interface DefaultOpticutInput {
  part: Omit<Part, 'id'>;
  material: Omit<Material, 'id'>;
  data: OptimizationInputExample;
}

const options: OptimizationOptionsDto = {
  minWaste: true,
  maxUtilization: true,
  smartPack: true,
  useInfiniteMaterials: true,
};

const opticutInputExample1: OptimizationInputExample = {
  name: 'Тестовый набор 1',
  parts: [
    {
      id: '1',
      length: 500,
      width: 300,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 10,
      canRotate: true,
      label: '1',
      description: 'Аквилон простой',
    },
    {
      id: '2',
      length: 400,
      width: 200,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 15,
      canRotate: true,
      label: '2',
      description: 'Откос оконный',
    },
    {
      id: '3',
      length: 800,
      width: 600,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 5,
      canRotate: true,
      label: '3',
      description: 'Соединительная планка простая',
    },
    {
      id: '4',
      length: 1200,
      width: 800,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 3,
      canRotate: true,
      label: '4',
      description: 'Угол внутренний простой',
    },
    {
      id: '5',
      length: 400,
      width: 400,
      color: '8017',
      thickness: 0.45,
      quantity: 12,
      canRotate: true,
      label: '5',
      description: 'Парапет трапецевидный',
    },
    {
      id: '6',
      length: 600,
      width: 300,
      color: '8017',
      thickness: 0.45,
      quantity: 8,
      canRotate: true,
      label: '6',
      description: 'Отлив для сендвич-панели',
    },
    {
      id: '7',
      length: 1000,
      width: 500,
      color: '8017',
      thickness: 0.45,
      quantity: 4,
      canRotate: true,
      label: '7',
      description: 'Примыкание пристенное подкровельное',
    },
    {
      id: '8',
      length: 2000,
      width: 350,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '8',
      description: 'Капельник нижний',
    },
    {
      id: '9',
      length: 1450,
      width: 950,
      color: '8017',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '9',
      description: 'Плинтус',
    },
    {
      id: '10',
      length: 290,
      width: 180,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '10',
      description: 'Нащельник прямоугольный',
    },
  ],

  availableMaterials: [
    {
      id: '1',
      length: 2000,
      width: 1250,
      color: 'Оцинкованный',
      thickness: 0.45,
      availableQuantity: 5,
    },
    {
      id: '2',
      length: 15000,
      width: 1250,
      color: 'Оцинкованный',
      thickness: 0.45,
      availableQuantity: 1,
    },
  ],

  options,
};

const opticutInputExample2: OptimizationInputExample = {
  ...opticutInputExample1,
  name: 'Тестовый набор 2',
  parts: [
    {
      id: '1',
      length: 1640,
      width: 230,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '1',
      description: 'Отлив',
    },
    {
      id: '2',
      length: 1640,
      width: 220,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '2',
      description: 'Угол наружный простой',
    },
    {
      id: '3',
      length: 2180,
      width: 225,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '3',
      description: 'Капельник',
    },
    {
      id: '4',
      length: 2180,
      width: 260,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '4',
      description: 'Конек простой',
    },
    {
      id: '5',
      length: 2000,
      width: 295,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '5',
      description: 'Парапет простой',
    },
    {
      id: '6',
      length: 2000,
      width: 395,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '6',
      description: 'Стартовая планка (начальная)',
    },
  ],
};

const opticutInputExample3: OptimizationInputExample = {
  ...opticutInputExample2,
  name: 'Тестовый набор 3',
  parts: [
    {
      id: '1',
      length: 2340,
      width: 175,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '2',
      length: 2320,
      width: 195,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '3',
      length: 1880,
      width: 170,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '4',
      length: 1960,
      width: 170,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '5',
      length: 1880,
      width: 180,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '6',
      length: 2540,
      width: 200,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '7',
      length: 1090,
      width: 165,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '8',
      length: 1540,
      width: 255,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '9',
      length: 1620,
      width: 245,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '10',
      length: 2240,
      width: 185,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '11',
      length: 2180,
      width: 185,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '12',
      length: 1740,
      width: 175,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '13',
      length: 2240,
      width: 165,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '14',
      length: 2230,
      width: 170,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '15',
      length: 2300,
      width: 310,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '16',
      length: 1120,
      width: 300,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '17',
      length: 1120,
      width: 260,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '18',
      length: 1120,
      width: 210,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '19',
      length: 2150,
      width: 320,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
  ],
};

const opticutInputExample4: OptimizationInputExample = {
  ...opticutInputExample1,
  name: 'Тестовый набор 4',
  parts: [
    {
      id: '1',
      length: 2540,
      width: 200,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '2',
      length: 2340,
      width: 175,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '3',
      length: 2320,
      width: 195,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '4',
      length: 2300,
      width: 310,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '5',
      length: 2240,
      width: 185,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '6',
      length: 2240,
      width: 165,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '7',
      length: 2200,
      width: 230,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '8',
      length: 2000,
      width: 220,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '9',
      length: 1900,
      width: 225,
      color: 'Оцинкованный',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
  ],
};

const opticutInputExample5: OptimizationInputExample = {
  name: 'Тестовый набор 5',
  parts: [
    {
      id: '1',
      length: 1450,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '2',
      length: 1100,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '3',
      length: 1100,
      width: 240,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '4',
      length: 1450,
      width: 140,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '5',
      length: 700,
      width: 140,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '6',
      length: 700,
      width: 170,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '7',
      length: 1750,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '8',
      length: 900,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '9',
      length: 900,
      width: 240,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '10',
      length: 1750,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '11',
      length: 900,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '12',
      length: 900,
      width: 240,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '13',
      length: 2150,
      width: 260,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '14',
      length: 1650,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '15',
      length: 1650,
      width: 240,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '16',
      length: 2150,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '17',
      length: 1690,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '18',
      length: 1690,
      width: 240,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '19',
      length: 2150,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '20',
      length: 1850,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '21',
      length: 1850,
      width: 240,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '22',
      length: 2150,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '23',
      length: 900,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '24',
      length: 900,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '25',
      length: 1700,
      width: 205,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '26',
      length: 900,
      width: 205,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '27',
      length: 900,
      width: 235,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '28',
      length: 2250,
      width: 200,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '29',
      length: 3240,
      width: 200,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '30',
      length: 3240,
      width: 215,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '31',
      length: 700,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '32',
      length: 1950,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '33',
      length: 3240,
      width: 215,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '34',
      length: 1550,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '35',
      length: 2300,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '36',
      length: 2300,
      width: 230,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '37',
      length: 1450,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '38',
      length: 900,
      width: 205,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '39',
      length: 900,
      width: 240,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '40',
      length: 1450,
      width: 210,
      color: '9003',
      thickness: 0.45,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '41',
      length: 2100,
      width: 205,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '42',
      length: 2100,
      width: 225,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '43',
      length: 2100,
      width: 205,
      color: '9003',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '44',
      length: 2000,
      width: 130,
      color: '1015',
      thickness: 0.45,
      quantity: 33,
      canRotate: true,
      label: '',
      description: '',
    },
  ],
  availableMaterials: [
    {
      id: '1',
      length: 99999,
      width: 1250,
      color: '9003',
      thickness: 0.45,
      availableQuantity: 2,
    },
    {
      id: '2',
      length: 99999,
      width: 1250,
      color: '1015',
      thickness: 0.45,
      availableQuantity: 2,
    },
  ],
  options,
};

const opticutInputExample6: OptimizationInputExample = {
  name: 'Тестовый набор 6',
  parts: [
    {
      id: '1',
      length: 2500,
      width: 150,
      color: '9003',
      thickness: 0.5,
      quantity: 174,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '2',
      length: 2500,
      width: 542,
      color: '9003',
      thickness: 0.5,
      quantity: 40,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '3',
      length: 2500,
      width: 312,
      color: '9003',
      thickness: 0.5,
      quantity: 160,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '4',
      length: 2500,
      width: 362,
      color: '9003',
      thickness: 0.5,
      quantity: 120,
      canRotate: true,
      label: '',
      description: '',
    },
  ],
  options,
};

const opticutInputExample7: OptimizationInputExample = {
  name: 'Тестовый набор 7',
  parts: [
    {
      id: '1',
      length: 2500,
      width: 150,
      color: '9003',
      thickness: 0.5,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '2',
      length: 2400,
      width: 542,
      color: '9003',
      thickness: 0.5,
      quantity: 4,
      canRotate: true,
      label: '',
      description: '',
    },
  ],
  options,
};

const opticutInputExample8: OptimizationInputExample = {
  name: 'Тестовый набор 8',
  parts: [
    {
      id: '1',
      length: 3000,
      width: 300,
      color: '8017',
      thickness: 0.5,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '2',
      length: 2500,
      width: 500,
      color: '8017',
      thickness: 0.5,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '3',
      length: 500,
      width: 150,
      color: '8017',
      thickness: 0.5,
      quantity: 2,
      canRotate: true,
      label: '',
      description: '',
    },
    {
      id: '4',
      length: 800,
      width: 100,
      color: '8017',
      thickness: 0.5,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
  ],
  options,
};

export const defaultOpticutDataList: OptimizationInputExample[] = [
  opticutInputExample1,
  opticutInputExample2,
  opticutInputExample3,
  opticutInputExample4,
  opticutInputExample5,
  opticutInputExample6,
  opticutInputExample7,
  opticutInputExample8,
];

export const defaultOpticutInput = (): DefaultOpticutInput => {
  const defaultData = { ...opticutInputExample6 };

  return {
    part: {
      length: 0,
      width: 0,
      color: '8017',
      thickness: 0.45,
      quantity: 1,
      canRotate: true,
      label: '',
      description: '',
    },
    material: {
      length: 0,
      width: 0,
      color: '8017',
      thickness: 0.45,
      availableQuantity: 0,
    },
    data: defaultData,
  };
};
